apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: place
  name: place-deployment
  namespace: place-namespace
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: place
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: place
    spec:
      containers:
      - image: gcr.io/stately-pulsar-310221/place@sha256:a70396c6905cec36c48a4baf656a1d9b7199fec57d780ff59237031ad14c98a7
        name: place-sha256-1
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 500m
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 500m


