apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: place
  name: place-deployment
  namespace: place-namespace
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: place
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: place
    spec:
      containers:
      - image: gcr.io/stately-pulsar-310221/place@sha256:ac93d930a471f9b9f1d5dc3e89a5870ce1987c77bf50450ced7c4d8d959ca783
        name: place-sha256-1
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 500m
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 500m


