apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: place
  name: place-deployment
  namespace: place-namespace
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: place
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: place
    spec:
      containers:
      - image: gcr.io/stately-pulsar-310221/place@sha256:6da61759e5c8467aa88e061d4d0cfe3ef0697fe1ae7520b375020753801ef2f6
        name: place-sha256-1
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 500m
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 500m


