spring:
  redis:
    host: ${REDIS_HOST:10.126.160.3}
    port: ${REDIS_PORT:6379}
    database: 0
    jedis:
      pool:
        min-idle: 2
        max-idle: 10
        max-wait: 10ms
        max-active: 10
security:
  basic:
    enabled: false

allowedOrigin: ${ALLOWED_ORIGIN:https://pxl.place}

